"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Header />
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
