import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./Header";
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="relative min-h-[100%]">
        <Header />
        <Navbar />
        <body className={inter.className}>{children}</body>
      </div>
    </html>
  );
}
